version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-xray
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /usr/local/etc/xray/config.json:/usr/local/etc/xray/config.json:rw
      - /etc/systemd/system:/etc/systemd/system:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./restart_xray.sh:/app/restart_xray.sh:rw
      - /var/log/squid/access.log:/var/log/squid/access.log:ro
