version: "3.9"

services:
  xray:
    image: teddysun/xray
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./xray/config.json:/etc/xray/config.json:rw       # rw — чтобы xray мог менять конфиг если надо
      - /etc/letsencrypt:/etc/letsencrypt:ro              # letsencrypt обычно readonly
      - ./logs/xray:/logs/xray:rw                          # логи — rw чтобы писать
    network_mode: host

  squid:
    image: ubuntu/squid
    container_name: squid
    restart: unless-stopped
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:rw       # rw — чтобы squid мог менять конфиг (если надо)
      - ./squid/passwd:/etc/squid/passwd:rw               # rw — чтобы squid мог читать/писать пароли
      - ./logs/squid:/logs/squid:rw                        # логи squid — rw
    network_mode: host

  fastapi:
    build:
      context: .
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app/app:rw
      - ./restart_xray.sh:/app/restart_xray.sh:rw

      - ./xray/config.json:/usr/local/etc/xray/config.json:rw

      - /etc/systemd/system:/etc/systemd/system:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - ./logs/xray/access.log:/logs/xray/access.log:rw   # rw — чтобы fastapi мог читать/писать логи
      - ./logs/xray/error.log:/logs/xray/error.log:rw
      - ./logs/squid/access.log:/logs/squid/access.log:rw

      - ./squid/passwd:/etc/squid/passwd:rw               # rw — fastapi тоже пускаем к passwd
    environment:
      - PYTHONUNBUFFERED=1
