version: "3.9"

services:
  xray:
    image: teddysun/xray
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./xray/config_hybrid.json:/etc/xray/config.json:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs/xray:/logs/xray
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"

  fastapi:
    build:
      context: .
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app/app
      - ./restart_xray.sh:/app/restart_xray.sh:rw
      - ./xray/config_hybrid.json:/usr/local/etc/xray/config.json:rw
      - /etc/systemd/system:/etc/systemd/system:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/xray/access.log:/logs/xray/access.log:ro
      - ./logs/xray/error.log:/logs/xray/error.log:ro
      - ./squid/passwd:/etc/squid/passwd:rw
    environment:
      - PYTHONUNBUFFERED=1
