version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-xray
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /usr/local/etc/xray/config.json:/usr/local/etc/xray/config.json:rw
