---
- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
  tags: [ssl, packages]

- name: Stop Nginx for standalone certificate generation
  systemd:
    name: nginx
    state: stopped
  tags: [ssl, certbot]

- name: Generate SSL certificate
  command: >
    certbot certonly 
    --standalone 
    --non-interactive 
    --agree-tos 
    --email {{ ssl_email }} 
    -d {{ domain }}
  register: certbot_result
  changed_when: certbot_result.rc == 0
  failed_when: certbot_result.rc != 0 and "already exists" not in certbot_result.stderr
  tags: [ssl, certbot]

- name: Start Nginx after certificate generation
  systemd:
    name: nginx
    state: started
  tags: [ssl, certbot]

- name: Setup automatic certificate renewal
  cron:
    name: "Renew SSL certificates"
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade"
    minute: "0"
    hour: "2"
    user: root
  tags: [ssl, cron]

- name: Test certificate renewal
  command: certbot renew --dry-run
  register: certbot_test
  changed_when: false
  tags: [ssl, test]
