---
- name: Create Squid configuration directory
  file:
    path: /opt/fastapi_xray/squid
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [squid, directories]

- name: Create Squid logs directory
  file:
    path: "{{ squid_logs_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [squid, directories]

- name: Generate Squid configuration
  template:
    src: squid.conf.j2
    dest: "{{ squid_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart squid
  tags: [squid, config]

- name: Generate Squid password file
  template:
    src: passwd.j2
    dest: "{{ squid_passwd_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart squid
  tags: [squid, config]

- name: Create Squid Docker Compose configuration
  template:
    src: docker-compose-squid.yml.j2
    dest: /opt/fastapi_xray/docker-compose-squid.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart squid
  tags: [squid, docker]

- name: Start Squid service
  systemd:
    name: squid
    state: started
    enabled: yes
  tags: [squid, service]
