---
- name: Reset UFW to defaults
  ufw:
    state: reset
  tags: [firewall, ufw]

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  tags: [firewall, ufw]

- name: Allow SSH access
  ufw:
    rule: allow
    port: "22"
    proto: tcp
  tags: [firewall, ufw]

- name: Allow HTTP and HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
  tags: [firewall, ufw]

- name: Allow FastAPI port
  ufw:
    rule: allow
    port: "{{ fastapi_port }}"
    proto: tcp
  tags: [firewall, ufw]

- name: Allow Squid port
  ufw:
    rule: allow
    port: "{{ squid_port }}"
    proto: tcp
  tags: [firewall, ufw]

- name: Enable UFW
  ufw:
    state: enabled
  tags: [firewall, ufw]

- name: Configure Fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: [firewall, fail2ban]

- name: Start and enable Fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  tags: [firewall, fail2ban]
