---
- name: Check connectivity to all VPN servers
  hosts: vpn_servers
  gather_facts: no
  
  tasks:
    - name: Test SSH connectivity
      ping:
      register: ping_result
      
    - name: Display connectivity status
      debug:
        msg: |
          Server: {{ inventory_hostname }}
          Country: {{ country }}
          IP: {{ ansible_host }}
          Status: {{ 'CONNECTED' if ping_result.ping == 'pong' else 'FAILED' }}
          
    - name: Check if server is reachable
      wait_for_connection:
        timeout: 30
      register: connection_result
      
    - name: Display connection details
      debug:
        msg: |
          Server: {{ inventory_hostname }}
          Connection: {{ 'SUCCESS' if connection_result.changed else 'FAILED' }}
          IP: {{ ansible_host }}
