---
- name: Manage Docker Compose services
  hosts: vpn_servers
  become: yes
  gather_facts: no
  
  vars:
    compose_action: "{{ action | default('up') }}"
    compose_build: "{{ build | default(false) }}"
    compose_detach: "{{ detach | default(true) }}"
  
  tasks:
    - name: Change to application directory
      ansible.builtin.set_fact:
        app_dir: /opt/fastapi_xray
    
    - name: Build and start services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
        recreate: always
        build: "{{ compose_build }}"
        pull: "{{ compose_build }}"
      when: compose_action == "up"
      tags: [compose, up]
    
    - name: Stop services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: absent
      when: compose_action == "down"
      tags: [compose, down]
    
    - name: Restart services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
        recreate: always
      when: compose_action == "restart"
      tags: [compose, restart]
    
    - name: Show running containers
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
      register: compose_status
      when: compose_action == "status"
      tags: [compose, status]
    
    - name: Display container status
      debug:
        msg: "{{ compose_status.containers }}"
      when: compose_action == "status" and compose_status is defined
      tags: [compose, status]
    
    - name: Show logs
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present
        logs: true
      when: compose_action == "logs"
      tags: [compose, logs]
