---
galaxy_info:
  author: VPN Service Team
  description: Install and configure Docker and Docker Compose
  company: VPN Service
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - docker
    - containers
    - deployment

dependencies: []
