---
galaxy_info:
  author: VPN Service Team
  description: SSL certificate management with Let's Encrypt
  company: VPN Service
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - ssl
    - certificates
    - letsencrypt
    - security

dependencies: []
